# Generated by Django 2.0.2 on 2020-06-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_IMG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_img',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
